apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
namespace: argo-app
images:
- name: argo-app
  newName: nhatns/argo-app
  newTag: b6e89ee80c3bff5af22553a924d9c28f5793bfdd
